### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by Laro88** [fmorbini/scxmlgui#87]
C:\Users\jera\Downloads>java -jar fsm-editor.jar
Restriction configuration file not found. The application starts in normal mode without restriction handling.
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBContext
        at com.mxgraph.examples.swing.SCXMLGraphEditor.<init>(SCXMLGraphEditor.java:538)
        at com.mxgraph.examples.swing.SCXMLGraphEditor.startEditor(SCXMLGraphEditor.java:1428)
        at com.mxgraph.examples.swing.SCXMLGraphEditor.main(SCXMLGraphEditor.java:1474)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBContext
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 3 more

**Comment by fmorbini** [comment]
Hi, if you are using java 11 it'll happen. you should use an older java. I'm not maintaining this project anymore. feel free to update the libraries to be able to run it on recent javas. In java 8 it still works fine. hope this helps.
